services:
  mongodb:
    image: 'mongo'
    volumes:
      - data:/data/db
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: khanye (unsecure if you sending via git)
      # Going for environment files, this is much safer
    env_file:
      - ./env/mongo.env
    networks:
      - backend
  npm:
    user: 1000:1000
    build: ./
    stdin_open: true
    tty: true
    volumes:
      - ./:/app
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - ./env/backend.env
    # This seems to be causing error when starting the npm container.
    depends_on:
      - mongodb
    networks:
      - backend
volumes:
  data:
networks:
  backend: {}